services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5101:5000"
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:///mlflow.db --artifacts-destination /mlartifacts --serve-artifacts --allowed-hosts "*"
    volumes:
      - ./mlflow_data:/mlartifacts
      - ./mlruns:/mlruns

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    ports:
      - "5102:8000"
    depends_on:
      - mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - ./data:/app/data
      - ./mlflow_data:/mlartifacts
