FROM python:3.12-slim

WORKDIR /opt/project

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY dataops/ ./dataops/
COPY mlops/ ./mlops/
COPY data/ ./data/

RUN pip install --no-cache-dir -e dataops/dagster_project/book_pipeline

ENV DAGSTER_HOME=/opt/dagster
ENV PYTHONPATH=/opt/project

RUN mkdir -p /opt/dagster